compile: compile4 compile5

compile4:
	ghc -o book_shop_4 -outputdir out Main4.hs

compile5:
	ghc -o book_shop_5 -outputdir out Main5.hs

main_4:
	./book_shop_4

main_5:
	./book_shop_5

clean:
	-rm out/*
	-rm book_shop_*
